### PR TITLE
Add multiprocessing support to ament_clang_tidy

### PR DESCRIPTION
**Pull request by mm318**
This can speedup the amount of time `ament_clang_tidy` spends analyzing/linting packages.

Without this change:
```
time ament_clang_tidy build/ > log_base.txt
real    2m18.908s
user    2m13.533s
sys     0m4.656s
```

With this change, using 1 job (default):
```
time ament_clang_tidy build/ > log_1cpu.txt
real    2m20.998s
user    2m15.870s
sys     0m4.364s
```
See log_1cpu.txt for 

With this change, using 4 parallel jobs:
```
time ament_clang_tidy --jobs 4 build/ > log_4cpu.txt
real    0m49.372s
user    2m20.114s
sys     0m4.619s
```

The attached log files also show that analysis results have not changed:
[log_base.txt](https://github.com/ament/ament_lint/files/5834324/log_base.txt)
[log_1cpu.txt](https://github.com/ament/ament_lint/files/5834322/log_1cpu.txt)
[log_4cpu.txt](https://github.com/ament/ament_lint/files/5834323/log_4cpu.txt)

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
I tested this locally and it greatly speeds up using ament_clang_tidy.

**Comment by mm318** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13454/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8365/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11178/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13518/)

**Comment by tylerjw** [comment]
> * Linux [Build Status](http://ci.ros2.org/job/ci_linux/13454/)
> 
> * Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8365/)
> 
> * macOS [Build Status](http://ci.ros2.org/job/ci_osx/11178/)
> 
> * Windows [Build Status](http://ci.ros2.org/job/ci_windows/13518/)

Minor aside, in the future would you like to migrate PR CI testing into GitHub actions?

**Comment by mm318** [comment]
> Minor aside, in the future would you like to migrate PR CI testing into GitHub actions?

I would like that, but it's not my call.

From my understanding, GitHub Actions now supports macOS and Windows, which is good.

It would probably be hard to make GitHub Actions support building and testing a arbitrary collection of ROS packages that depend on each other. This may be acceptable for the `ament_lint` repo, but probably not for the other `ament` repos or the ROS2 core repos.

**Comment by tylerjw** [comment]
> It would probably be hard to make GitHub Actions support building and testing a arbitrary collection of ROS packages that depend on each other. This may be acceptable for the `ament_lint` repo, but probably not for the other `ament` repos or the ROS2 core repos.

I think this is actually fairly doable using https://github.com/ros-industrial/industrial_ci

If you'd like I can try to create a PR to do this.  Can you point me to how the CI on jenkins is configured?

**Comment by mm318** [comment]
> If you'd like I can try to create a PR to do this. Can you point me to how the CI on jenkins is configured?

I don't mind. But it would probably take convincing more than a couple of people at OSRF to move PR CI testing from Jenkins to GitHub Actions.

If you follow the link in the badges (for example, https://ci.ros2.org/job/ci_linux/13454/), it shows the repos file, the Ubuntu distro, ROS distro, `colcon build --packages-up-to`, and `colcon test --packages-select` options used. These options were chosen by me specifically for this PR. Not sure if that's the kind of configuration details you were looking for.

OSRF does require testing on Windows and macOS before merging. So while GitHub Actions does support Windows and macOS, ROS Industrial's CI might not.

**Comment by tylerjw** [comment]
On topic, this looks like it needs to be rebased for the doc change.  I'm looking forward to using this feature.  I'm curious if you have any idea how it could be used from colcon/cmake.  Do linters already run in parallel when launched from colcon (once thread project up to system threads or -j option)?

**Comment by mm318** [comment]
Re-running CI after merging in `master` branch:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13465/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8376/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11189/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13529/)

**Comment by mm318** [comment]
@claireyywang, would you mind reviewing this PR, too? I think it is a highly sought after feature :)

**Comment by mm318** [comment]
> I'm curious if you have any idea how it could be used from colcon/cmake.

I am not familiar with how `colcon` invokes things. But I believe changes need to made on the CMake side, particularly passing `--jobs` into `ament_add_test()` at https://github.com/ament/ament_lint/blob/14fa404980cc55d36d45c02f04f09f5dd36fd10a/ament_cmake_clang_tidy/cmake/ament_clang_tidy.cmake#L58
What that number should be passed in should probably be dynamically determined by CMake or `make`, so that when you're building multiple packages in parallel, you don't get a massive number of `clang-tidy` processes spawned.

> Do linters already run in parallel when launched from colcon (once thread project up to system threads or -j option)?

I think `colcon test` invokes `make test -j <number of cores>`, which probably runs different linters in parallel, but each linter will use its default number of threads.

**Comment by mm318** [comment]
@claireyywang, friendly ping. Or if you could get another maintainer to take a look. Thanks!

**Review by claireyywang — APPROVED** [review]
LGTM

**Pull request merged**
