### PR TITLE
ignore cpplint runtime/int error

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please review.

**Comment by esteve** [comment]
Wouldn't it be better to actually change `int` / `long` to sized integers in our code? (e.g. int32, int64, etc.)

**Comment by dirk-thomas** [comment]
That would be an alternative. Could you work on create PRs for that instead? Then we don't have to ignore this cpplint warning.

**Comment by esteve** [comment]
Is there a log of cpplint on the buildfarm to see the warnings?

**Comment by dirk-thomas** [comment]
No, I only ran the tests with ament_cmake_cpplint added as a default linter locally.

**Comment by tfoote** [comment]
We'll merge this as is. And open a ticket to clean up the usage and let us revert this later.

**Pull request merged**
