### PR TITLE
ament_pclint: Fixing copyright and formatting issues.

### PR DESCRIPTION
**Pull request by mjcarroll**
This is a rework of #98 but with some style issues resolved.

### CODE REVIEW

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4727/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1595/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3917/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4788/)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4728/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1596/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3918/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4789/)

**Comment by mikaelarguedas** [comment]
Note to self: this will require a new release of ament_lint

**Comment by mikaelarguedas** [comment]
@mjcarroll can you please adapt the package.xml and setup.py of this PR to use the same version number as the other packages of this repo (0.5.1) ? thanks!

**Pull request merged**
