### PR TITLE
split linter packages in python and cmake

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ament/ament_lint#11.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Color to dependency type:
* red: build
* green: run
* blue: test

ament_lint_graph

**Comment by esteve** [comment]
> red: build
> green: run

 (╯°□°）╯︵ ┻━┻

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Pull request merged**
