### PR TITLE
support flake8 3.8 while maintaining compatibility with older versions

### PR DESCRIPTION
**Pull request by dirk-thomas**
CI builds only testing `ament_flake8` and `ament_index_python`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10707/)
  * Same parameters but testing with `master`: [Build Status](https://ci.ros2.org/job/ci_linux/10708/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6120/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8721/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10607/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am going ahead and merge this without review to avoid all nightly jobs to fail all `flake8` tests. Feel free to comment after the fact.

**Comment by emersonknapp** [comment]
Can/should this be backported to Eloquent? The flake8 update will affect Bionic users who install flake8 via pip, as per the [build from source instructions](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/#install-development-tools-and-ros-tools)

**Comment by dirk-thomas** [comment]
> Can/should this be backported to Eloquent?

@mjcarroll to decide.

**Comment by emersonknapp** [comment]
Note that this also affects Dashing on Bionic - so our LTS is broken

**Pull request merged**
