### PR TITLE
fix name of included CMake file for cmake_clang_format

### PR DESCRIPTION
**Pull request by dirk-thomas**
Based on https://answers.ros.org/question/317464/ament_cmake_clang_format-fails-to-find-ament_clang_format-package/

### CODE REVIEW

**Comment by AnticliMaxtic** [comment]
Using the same setup as in https://answers.ros.org/question/317464/ament_cmake_clang_format-fails-to-find-ament_clang_format-package/ (where I posted) I now get this error
```
CMake Error at /root/ros2_ws/ros2_base/install/ament_cmake_clang_format/share/ament_cmake_clang_format/cmake/ament_clang_format.cmake:35 (message):
  ament_clang_format() variable 'ament_clang_format_BIN' must not be empty
Call Stack (most recent call first):
  /root/ros2_ws/ros2_base/install/ament_cmake_clang_format/share/ament_cmake_clang_format/cmake/ament_cmake_clang_format_lint_hook.cmake:27 (ament_clang_format)
  /root/ros2_ws/ros2_base/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:38 (include)
  /root/ros2_ws/ros2_base/install/ament_lint_auto/share/ament_lint_auto/cmake/ament_lint_auto_package_hook.cmake:15 (ament_execute_extensions)
  /root/ros2_ws/ros2_base/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:38 (include)
  /root/ros2_ws/ros2_base/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_package.cmake:66 (ament_execute_extensions)
  CMakeLists.txt:65 (ament_package)


---
```

**Comment by dirk-thomas** [comment]
Thanks for keep reporting problems. I guess that specific linter has never worked / was never used. I added a commit to the PR - please try it again.

**Comment by AnticliMaxtic** [comment]
Awesome, works like a charm. Glad I could be of some use :stuck_out_tongue_winking_eye: and thanks for the updates!

**Comment by dirk-thomas** [comment]
> CI might be reasonable to do so in order to make sure that slotting in the python executable works on all platforms

Running CI doesn't make sense since even the completely broken state before the patch never raised a flag since it isn't being used anywhere.

**Pull request merged**
