### PR TITLE
Add optional file header style

### LINKED ISSUE #303: Alternative License Header Option for ament_copyright
As in Google's Open Source documentation [here](https://opensource.google/docs/releasing/licenses/), there's an alternative way to put a license on the header of each source code. I think the ament_copyright linter should be able to check a license header from that option too.

### PR DESCRIPTION
**Pull request by threeal**
Closes #303

### CODE REVIEW

**Comment by tfoote** [comment]
Thanks for helping extend this. It will make things easier for many people.

**Review by audrow — APPROVED** [review]
Looks good. Thanks for the PR, @threeal. We can merge this in with green CI.

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13932/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8774/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11636/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14018/)

**Comment by audrow** [comment]
Once the linter warning is taken care of, this should be good to go. @threeal, let me know if you need any help with this.

**Comment by threeal** [comment]
@audrow sorry, i just know if you waiting me to fix this, will do it ASAP.

**Comment by audrow** [comment]
Here's a new CI run of Linux. If it's green I'll run the other three. I'm not sure why the PR jobs is failing.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13946/)

**Comment by audrow** [comment]
@ros-pull-request-builder retest this please

**Comment by audrow** [comment]
CI after a rebase:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13949/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8786/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11652/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14034/)

**Comment by audrow** [comment]
The CI errors are a known bug: https://github.com/ros2/demos/issues/490.

**Comment by audrow** [comment]
Thanks for the PR, @threeal!

**Pull request merged**
