### PR TITLE
ament_lint_cmake: default linelength in argumentparser for consistency

### LINKED ISSUE #301: CMake linter default line length differs depending on invocation
* Using `ament_lint_cmake` entrypoing from shell - defaults to 80 chars from https://github.com/ament/ament_lint/blob/master/ament_lint_cmake/ament_lint_cmake/cmakelint.py#L87
* Using `ament_cmake_lint_cmake` to call `ament_lint_cmake()` from `CMakeLists.txt` -  it defaults to 140 chars because of https://github.com/ament/ament_lint/blob/master/ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake#L44

This means that, given no external configurations, calling the same tool two ways can have different results. Not sure what the best way to resolve this is - my first thought is to add a `default=140` to the [ArgumentParser](https://github.com/ament/ament_lint/blob/master/ament_lint_cmake/ament_lint_cmake/main.py#L52) - and to _remove_ the [CMake default](https://github.com/ament/ament_lint/blob/master/ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake#L44) to avoid duplicate information

### PR DESCRIPTION
**Pull request by emersonknapp**
Fixes #301 
Related to https://github.com/ros-tooling/action-ros-lint/pull/246

### CODE REVIEW

**Comment by emersonknapp** [comment]
@audrow review please :)

**Review by audrow — APPROVED** [review]
Looks good!

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13939/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8780/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11642/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14026/)

**Comment by audrow** [comment]
The CI failures appear to be in the nightly as well: https://ci.ros2.org/view/nightly/job/nightly_linux_release/1852/.

**Comment by audrow** [comment]
Thanks for the PR, @emersonknapp!

**Pull request merged**
